### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by miniBill** [SecularSolstice/SecularSolstice.github.io#27]
I am working on improving the general state of this repository. Would you accept a pull request that moves all the songs in a `songs` subdirectory?

Pros:
 - cleaner structure,
 - will enable simplifying the Makefiles.

Cons:
 - would break existing benchmarks.

**Comment by dspeyer** [comment]
Sure, go for it.

Make sure to edit all relevant scripts.  Which is probably all of them, or
very close to it.
